config/routes.rb
Railskurs::Application.routes.draw do
  resources :courses

  root :to => "courses#index"

end

app/models/course.rb
class Course < ActiveRecord::Base
  validates_presence_of :code, :name, :credit, :assessments, :mandatory_activities, :teacher
  validates_numericality_of :credit, :assessments, :mandatory_activities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.xml
  def index
    @courses = Course.all
    @course = Course.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    #@course = Course.new(params[:course])

    require 'ntnu/api/client'

    course_code = params[:course][:code]
    @course = NTNU::API::CourseClient.get_course(course_code)

    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div class="course">
    <a href="<%= course_path(course) %>">
    <span class="course-code" title="<%= course.name %>"><%= course.code %></span>
    </a>
</div>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.text_field :code, :size => 9, :placeholder => "Course code" %>
    <%= f.submit "Get course" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<header>
  <h2>My courses</h2>
  <p>TODO: List all courses.</p>
  <div id="course-list">
    <%= render @courses %>
  </div>
</header>

<h3>Add course</h3>
<div class="align-center">
  <%= render 'form' %>
</div>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div id="course-details">
    <header>
      <h3>
        <span class="course-code"><%= @course.code %></span>
      </h3>
    </header>
  
    TODO: Implement more!
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="no">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>BEKK - Avansert Ruby on Rails kurs: Del 3</title>
  <meta name="author" content="Bekk Consulting AS">

  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header-container">
		<header class="wrapper">
			<h1 id="title">Enterprise Course Manager</h1>
			<nav>
				<ul>
					<li><a href="#2">Some</a></li>
					<li><a href="#">navigation</a></li>
					<li><a href="#">links</a></li>
				</ul>
			</nav>
		</header>
	</div>
	<div id="main" class="wrapper">
      <article>
        <%= yield %>
      </article>
	</div>
	<div id="footer-container">
		<footer class="wrapper">
			<h3>A nice footer</h3>
		</footer>
	</div>

</body>
</html>